# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic



matrix:
  include:
  - env: CONFIG=linux_ppc64le_SYMBOLSUFFIX64_USE_OPENMP0name_suffix-ilp64 UPLOAD_PACKAGES=True
      PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
    os: linux
    arch: ppc64le
    dist: focal

  - env: CONFIG=linux_ppc64le_SYMBOLSUFFIX64_USE_OPENMP1name_suffix-ilp64 UPLOAD_PACKAGES=True
      PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
    os: linux
    arch: ppc64le
    dist: focal

  - env: CONFIG=linux_ppc64le_SYMBOLSUFFIXUSE_OPENMP0name_suffix UPLOAD_PACKAGES=True
      PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
    os: linux
    arch: ppc64le
    dist: focal

  - env: CONFIG=linux_ppc64le_SYMBOLSUFFIXUSE_OPENMP1name_suffix UPLOAD_PACKAGES=True
      PLATFORM=linux-ppc64le DOCKER_IMAGE=quay.io/condaforge/linux-anvil-ppc64le
    os: linux
    arch: ppc64le
    dist: focal

script:
- export CI=travis
- export GIT_BRANCH="$TRAVIS_BRANCH"
- export FEEDSTOCK_NAME=$(basename ${TRAVIS_REPO_SLUG})


- if [[ ${PLATFORM} =~ .*linux.* ]]; then ./.scripts/run_docker_build.sh; fi
